export const SELECT_DEFAULT_CARD_REQUEST = 'SELECT_DEFAULT_CARD_REQUEST';
export const SELECT_DEFAULT_CARD_SUCCESS = 'SELECT_DEFAULT_CARD_SUCCESS';
export const SELECT_DEFAULT_CARD_FAILURE = 'SELECT_DEFAULT_CARD_FAULURE';

export const CLEAR_VISITOR_LIST = 'CLEAR_VISITOR_LIST';
export const INSERT_VISITOR_LIST = 'INSERT_VISITOR_LIST';
export const DELETE_VISITOR_LIST = 'DELETE_VISITOR_LIST';
export const UPDATE_VISITOR_LIST = 'UPDATE_VISITOR_LIST';
export const SELECT_VISITOR_LIST = 'SELECT_VISITOR_LIST';
export const CLEAR_REGISTER_LIST = 'CLEAR_REGISTER_LIST';
export const SELECT_REGISTER_LIST = 'SELECT_REGISTER_LIST';
export const CLEAR_SUBSCRIBE_LIST = 'CLEAR_SUBSCRIBE_LIST';
export const SELECT_SUBSCRIBE_LIST = 'SELECT_SUBSCRIBE_LIST';
// 已支付记录请求类型
export const SELECT_ISPAYED_RECORDS_REQUEST = 'SELECT_ISPAYED_RECORDS_REQUEST';
export const SELECT_ISPAYED_RECORDS_SUCCESS = 'SELECT_ISPAYED_RECORDS_SUCCESS';
export const SELECT_ISPAYED_RECORDS_FAILURE = 'SELECT_ISPAYED_RECORDS_FAILURE';
// 未支付记录请求类型
export const SELECT_NOPAYED_RECORDS_REQUEST = 'SELECT_NOPAYED_RECORDS_REQUEST';
export const SELECT_NOPAYED_RECORDS_SUCCESS = 'SELECT_NOPAYED_RECORDS_SUCCESS';
export const SELECT_NOPAYED_RECORDS_FAILURE = 'SELECT_NOPAYED_RECORDS_FAILURE';
