// 查询设备标识
export const SELECT_DEVICEID_REQUEST = 'SELECT_DEVICEID_REQUEST';
export const SELECT_DEVICEID_SUCCESS = 'SELECT_DEVICEID_SUCCESS';
export const SELECT_DEVICEID_FAILURE = 'SELECT_DEVICEID_FAILURE';
// 非静默方式登录获取用户信息
export const SELECT_GRANT_LOGIN_REQUEST = 'SELECT_GRANT_LOGIN_REQUEST';
export const SELECT_GRANT_LOGIN_SUCCESS = 'SELECT_GRANT_LOGIN_SUCCESS';
export const SELECT_GRANT_LOGIN_FAILURE = 'SELECT_GRANT_LOGIN_FAILURE';
// 查询JSSDK的Token
export const SELECT_WECHAT_TOKEN_REQUEST = 'SELECT_WECHAT_TOKEN_REQUEST';
export const SELECT_WECHAT_TOKEN_SUCCESS = 'SELECT_WECHAT_TOKEN_SUCCESS';
export const SELECT_WECHAT_TOKEN_FAILURE = 'SELECT_WECHAT_TOKEN_FAILURE';
// 非静默方式登录获取用户信息
export const SELECT_JSSDK_CONFIG_REQUEST = 'SELECT_JSSDK_CONFIG_REQUEST';
export const SELECT_JSSDK_CONFIG_SUCCESS = 'SELECT_JSSDK_CONFIG_SUCCESS';
export const SELECT_JSSDK_CONFIG_FAILURE = 'SELECT_JSSDK_CONFIG_FAILURE';
// 查询默认就诊卡
export const SELECT_DEFAULT_CARD_REQUEST = 'SELECT_DEFAULT_CARD_REQUEST';
export const SELECT_DEFAULT_CARD_SUCCESS = 'SELECT_DEFAULT_CARD_SUCCESS';
export const SELECT_DEFAULT_CARD_FAILURE = 'SELECT_DEFAULT_CARD_FAILURE';
// 查询推送消息
export const SELECT_MESSAGE_LIST_REQUEST = 'SELECT_MESSAGE_LIST_REQUEST';
export const SELECT_MESSAGE_LIST_SUCCESS = 'SELECT_MESSAGE_LIST_SUCCESS';
export const SELECT_MESSAGE_LIST_FAILURE = 'SELECT_MESSAGE_LIST_FAILURE';
// 新增就诊卡
export const INSERT_VISITOR_LIST_REQUEST = 'INSERT_VISITOR_LIST_REQUEST';
export const INSERT_VISITOR_LIST_SUCCESS = 'INSERT_VISITOR_LIST_SUCCESS';
export const INSERT_VISITOR_LIST_FAILURE = 'INSERT_VISITOR_LIST_FAILURE';
// 删除就诊卡
export const DELETE_VISITOR_LIST_REQUEST = 'DELETE_VISITOR_LIST_REQUEST';
export const DELETE_VISITOR_LIST_SUCCESS = 'DELETE_VISITOR_LIST_SUCCESS';
export const DELETE_VISITOR_LIST_FAILURE = 'DELETE_VISITOR_LIST_FAILURE';
// 更新就诊卡
export const UPDATE_VISITOR_LIST_REQUEST = 'UPDATE_VISITOR_LIST_REQUEST';
export const UPDATE_VISITOR_LIST_SUCCESS = 'UPDATE_VISITOR_LIST_SUCCESS';
export const UPDATE_VISITOR_LIST_FAILURE = 'UPDATE_VISITOR_LIST_FAILURE';
// 查询就诊卡
export const SELECT_VISITOR_LIST_REQUEST = 'SELECT_VISITOR_LIST_REQUEST';
export const SELECT_VISITOR_LIST_SUCCESS = 'SELECT_VISITOR_LIST_SUCCESS';
export const SELECT_VISITOR_LIST_FAILURE = 'SELECT_VISITOR_LIST_FAILURE';
// 查询我的预约
export const SELECT_REGISTER_LIST_REQUEST = 'SELECT_REGISTER_LIST_REQUEST';
export const SELECT_REGISTER_LIST_SUCCESS = 'SELECT_REGISTER_LIST_SUCCESS';
export const SELECT_REGISTER_LIST_FAILURE = 'SELECT_REGISTER_LIST_FAILURE';
// 清空我的预约
export const CLEAR_REGISTER_LIST_SUCCESS = 'CLEAR_REGISTER_LIST_SUCCESS';
// 取消预约
export const DELETE_REGISTER_LIST_REQUEST = 'DELETE_REGISTER_LIST_REQUEST';
export const DELETE_REGISTER_LIST_SUCCESS = 'DELETE_REGISTER_LIST_SUCCESS';
export const DELETE_REGISTER_LIST_FAILURE = 'DELETE_REGISTER_LIST_FAILURE';
// 预约取号
export const INSERT_DOREGISTER_LIST_REQUEST = 'INSERT_DOREGISTER_LIST_REQUEST';
export const INSERT_DOREGISTER_LIST_SUCCESS = 'INSERT_DOREGISTER_LIST_SUCCESS';
export const INSERT_DOREGISTER_LIST_FAILURE = 'INSERT_DOREGISTER_LIST_FAILURE';
// 查询我的挂号
export const SELECT_SUBSCRIBE_LIST_REQUEST = 'SELECT_SUBSCRIBE_LIST_REQUEST';
export const SELECT_SUBSCRIBE_LIST_SUCCESS = 'SELECT_SUBSCRIBE_LIST_SUCCESS';
export const SELECT_SUBSCRIBE_LIST_FAILURE = 'SELECT_SUBSCRIBE_LIST_FAILURE';
// 清空我的预约挂号
export const CLEAR_SUBCRIBE_LIST_SUCCESS = 'CLEAR_SUBCRIBE_LIST_SUCCESS';
// 取消我的预约挂号
export const DELETE_SUBSCRIBE_LIST_REQUEST = 'DELETE_SUBSCRIBE_LIST_REQUEST';
export const DELETE_SUBSCRIBE_LIST_SUCCESS = 'DELETE_SUBSCRIBE_LIST_SUCCESS';
export const DELETE_SUBSCRIBE_LIST_FAILURE = 'DELETE_SUBSCRIBE_LIST_FAILURE';
// 已支付记录请求类型
export const SELECT_ISPAYED_RECORDS_REQUEST = 'SELECT_ISPAYED_RECORDS_REQUEST';
export const SELECT_ISPAYED_RECORDS_SUCCESS = 'SELECT_ISPAYED_RECORDS_SUCCESS';
export const SELECT_ISPAYED_RECORDS_FAILURE = 'SELECT_ISPAYED_RECORDS_FAILURE';
// 未支付记录请求类型
export const SELECT_NOPAYED_RECORDS_REQUEST = 'SELECT_NOPAYED_RECORDS_REQUEST';
export const SELECT_NOPAYED_RECORDS_SUCCESS = 'SELECT_NOPAYED_RECORDS_SUCCESS';
export const SELECT_NOPAYED_RECORDS_FAILURE = 'SELECT_NOPAYED_RECORDS_FAILURE';
// 代缴费去支付
export const SELECT_PAY_REGISTER_REQUEST = 'SELECT_PAY_REGISTER_REQUEST';
export const SELECT_PAY_REGISTER_SUCCESS = 'SELECT_PAY_REGISTER_SUCCESS';
export const SELECT_PAY_REGISTER_FAILURE = 'SELECT_PAY_REGISTER_FAILURE';
// 未支付记录请求类型
export const SELECT_DOCTOR_LIST_REQUEST = 'SELECT_DOCTOR_LIST_REQUEST';
export const SELECT_DOCTOR_LIST_SUCCESS = 'SELECT_DOCTOR_LIST_SUCCESS';
export const SELECT_DOCTOR_LIST_FAILURE = 'SELECT_DOCTOR_LIST_FAILURE';
// 发起支付请求
export const SELECT_REGISTER_PAY_REQUEST = 'SELECT_REGISTER_PAY_REQUEST';
export const SELECT_REGISTER_PAY_SUCCESS = 'SELECT_REGISTER_PAY_SUCCESS';
export const SELECT_REGISTER_PAY_FAILURE = 'SELECT_REGISTER_PAY_FAILURE';
// 查询排班科室
export const SELECT_DEPARTMENT_REQUEST = 'SELECT_DEPARTMENT_REQUEST';
export const SELECT_DEPARTMENT_SUCCESS = 'SELECT_DEPARTMENT_SUCCESS';
export const SELECT_DEPARTMENT_FAILURE = 'SELECT_DEPARTMENT_FAILURE';
// 查询子级科室
export const SELECT_SUB_DEPARTMENT_REQUEST = 'SELECT_SUB_DEPARTMENT_REQUEST';
export const SELECT_SUB_DEPARTMENT_SUCCESS = 'SELECT_SUB_DEPARTMENT_SUCCESS';
export const SELECT_SUB_DEPARTMENT_FAILURE = 'SELECT_SUB_DEPARTMENT_FAILURE';
// 查询医生详情
export const SELECT_DOCTOR_DETAIL_REQUEST = 'SELECT_DOCTOR_DETAIL_REQUEST';
export const SELECT_DOCTOR_DETAIL_SUCCESS = 'SELECT_DOCTOR_DETAIL_SUCCESS';
export const SELECT_DOCTOR_DETAIL_FAILURE = 'SELECT_DOCTOR_DETAIL_FAILURE';
// 查询科室详情
export const SELECT_DEPT_DETAIL_REQUEST = 'SELECT_DEPT_DETAIL_REQUEST';
export const SELECT_DEPT_DETAIL_SUCCESS = 'SELECT_DEPT_DETAIL_SUCCESS';
export const SELECT_DEPT_DETAIL_FAILURE = 'SELECT_DEPT_DETAIL_FAILURE';
// 查询检验报告详情
export const SELECT_REPORT_LIST_REQUEST = 'SELECT_REPORT_LIST_REQUEST';
export const SELECT_REPORT_LIST_SUCCESS = 'SELECT_REPORT_LIST_SUCCESS';
export const SELECT_REPORT_LIST_FAILURE = 'SELECT_REPORT_LIST_FAILURE';
// 新增健康档案
export const INSERT_HEALTH_LIST_REQUEST = 'INSERT_HEALTH_LIST_REQUEST';
export const INSERT_HEALTH_LIST_SUCCESS = 'INSERT_HEALTH_LIST_SUCCESS';
export const INSERT_HEALTH_LIST_FAILURE = 'INSERT_HEALTH_LIST_FAILURE';
// 查询健康档案
export const SELECT_HEALTH_LIST_REQUEST = 'SELECT_HEALTH_LIST_REQUEST';
export const SELECT_HEALTH_LIST_SUCCESS = 'SELECT_HEALTH_LIST_SUCCESS';
export const SELECT_HEALTH_LIST_FAILURE = 'SELECT_HEALTH_LIST_FAILURE';
// 查询预约挂号支付信息
export const SELECT_APPO_CREATE_REQUEST = 'SELECT_APPO_CREATE_REQUEST';
export const SELECT_APPO_CREATE_SUCCESS = 'SELECT_APPO_CREATE_SUCCESS';
export const SELECT_APPO_CREATE_FAILURE = 'SELECT_APPO_CREATE_FAILURE';
// 查询挂号支付信息
export const SELECT_TODAY_CREATE_REQUEST = 'SELECT_TODAY_CREATE_REQUEST';
export const SELECT_TODAY_CREATE_SUCCESS = 'SELECT_TODAY_CREATE_SUCCESS';
export const SELECT_TODAY_CREATE_FAILURE = 'SELECT_TODAY_CREATE_FAILURE';
