// 查询设备标识
export const SELECT_DEVICEID_REQUEST = 'SELECT_DEVICEID_REQUEST';
export const SELECT_DEVICEID_SUCCESS = 'SELECT_DEVICEID_SUCCESS';
export const SELECT_DEVICEID_FAILURE = 'SELECT_DEVICEID_FAILURE';
// 静默方式登录获取用户信息
export const SELECT_AUTO_LOGIN_REQUEST = 'SELECT_AUTO_LOGIN_REQUEST';
export const SELECT_AUTO_LOGIN_SUCCESS = 'SELECT_AUTO_LOGIN_SUCCESS';
export const SELECT_AUTO_LOGIN_FAILURE = 'SELECT_AUTO_LOGIN_FAILURE';
// 非静默方式登录获取用户信息
export const SELECT_MANU_LOGIN_REQUEST = 'SELECT_MANU_LOGIN_REQUEST';
export const SELECT_MANU_LOGIN_SUCCESS = 'SELECT_MANU_LOGIN_SUCCESS';
export const SELECT_MANU_LOGIN_FAILURE = 'SELECT_MANU_LOGIN_FAILURE';
// 查询默认就诊卡
export const SELECT_DEFAULT_CARD_REQUEST = 'SELECT_DEFAULT_CARD_REQUEST';
export const SELECT_DEFAULT_CARD_SUCCESS = 'SELECT_DEFAULT_CARD_SUCCESS';
export const SELECT_DEFAULT_CARD_FAILURE = 'SELECT_DEFAULT_CARD_FAILURE';
// 新增就诊卡
export const INSERT_VISITOR_LIST_REQUEST = 'INSERT_VISITOR_LIST_REQUEST';
export const INSERT_VISITOR_LIST_SUCCESS = 'INSERT_VISITOR_LIST_SUCCESS';
export const INSERT_VISITOR_LIST_FAILURE = 'INSERT_VISITOR_LIST_FAILURE';
// 删除就诊卡
export const DELETE_VISITOR_LIST_REQUEST = 'DELETE_VISITOR_LIST_REQUEST';
export const DELETE_VISITOR_LIST_SUCCESS = 'DELETE_VISITOR_LIST_SUCCESS';
export const DELETE_VISITOR_LIST_FAILURE = 'DELETE_VISITOR_LIST_FAILURE';
// 更新就诊卡
export const UPDATE_VISITOR_LIST_REQUEST = 'UPDATE_VISITOR_LIST_REQUEST';
export const UPDATE_VISITOR_LIST_SUCCESS = 'UPDATE_VISITOR_LIST_SUCCESS';
export const UPDATE_VISITOR_LIST_FAILURE = 'UPDATE_VISITOR_LIST_FAILURE';
// 查询就诊卡
export const SELECT_VISITOR_LIST_REQUEST = 'SELECT_VISITOR_LIST_REQUEST';
export const SELECT_VISITOR_LIST_SUCCESS = 'SELECT_VISITOR_LIST_SUCCESS';
export const SELECT_VISITOR_LIST_FAILURE = 'SELECT_VISITOR_LIST_FAILURE';
// 查询我的预约
export const SELECT_REGISTER_LIST_REQUEST = 'SELECT_REGISTER_LIST_REQUEST';
export const SELECT_REGISTER_LIST_SUCCESS = 'SELECT_REGISTER_LIST_SUCCESS';
export const SELECT_REGISTER_LIST_FAILURE = 'SELECT_REGISTER_LIST_FAILURE';
// 查询我的挂号
export const SELECT_SUBSCRIBE_LIST_REQUEST = 'SELECT_SUBSCRIBE_LIST_REQUEST';
export const SELECT_SUBSCRIBE_LIST_SUCCESS = 'SELECT_SUBSCRIBE_LIST_SUCCESS';
export const SELECT_SUBSCRIBE_LIST_FAILURE = 'SELECT_SUBSCRIBE_LIST_FAILURE';
// 已支付记录请求类型
export const SELECT_ISPAYED_RECORDS_REQUEST = 'SELECT_ISPAYED_RECORDS_REQUEST';
export const SELECT_ISPAYED_RECORDS_SUCCESS = 'SELECT_ISPAYED_RECORDS_SUCCESS';
export const SELECT_ISPAYED_RECORDS_FAILURE = 'SELECT_ISPAYED_RECORDS_FAILURE';
// 未支付记录请求类型
export const SELECT_NOPAYED_RECORDS_REQUEST = 'SELECT_NOPAYED_RECORDS_REQUEST';
export const SELECT_NOPAYED_RECORDS_SUCCESS = 'SELECT_NOPAYED_RECORDS_SUCCESS';
export const SELECT_NOPAYED_RECORDS_FAILURE = 'SELECT_NOPAYED_RECORDS_FAILURE';
